import Head from 'next/head';
import Header from './Header';

function Layout({children}) {
  return (
    <>
      <Head>
        <title>Context reducer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen bg-gray-900 text-white">
        
        <Header />
        
        <main className="px-28 py-10">
          {children}
        </main>

      </div>

    </>
  )
}

export default Layout;
